language: python
python:
- '3.4'
- '3.3'
- '3.2'
- '2.7'
- '2.6'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libboost-python1.48-dev
install:
- pip install -r requirements.txt --use-mirrors
before_script:
- rm -rf src/smhasher
- svn checkout http://smhasher.googlecode.com/svn/trunk/ src/smhasher
script:
- sudo python setup.py test
deploy:
  provider: releases
  api_key:
    secure: ToYiWDZVLRIXArdeo8SANYlgcontxCODh8g4CuCVpz26KuIQ9HttDN0ENF+5JrRmVVo6dA3P9WjRh210uLqoldA07lTieNJrwo5ubD40TVlvCdylOvwm2Pm7oF59ws19GohA04ZUAAlJMqryeA2XgENg1x1av8wALUtmi9dNwH8=
  file: dist/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: flier/pyfasthash
