sudo: false
language: python
cache: pip
python:
  - '3.7-dev'
  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'
  - 'pypy2.7-5.10'
  - 'pypy3.5'
install:
  - pip install -U setuptools pip
  - pip install -r requirements.txt -r tests/requirements.txt
  - pip install .
script:
  - pytest -v
