language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-python1.48-dev
install:
  - pip install -r requirements.txt --use-mirrors
before_script:
  - rm -rf src/smhasher
  - svn checkout http://smhasher.googlecode.com/svn/trunk/ src/smhasher
script:
  - sudo python setup.py test
