sudo: false
language: python
os:
  - linux
  - osx
python:
  - '3.7-dev'
  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'
  - '2.6'
  - 'pypy2.7'
  - 'pypy3.5'
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - python setup.py test
