language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
before_install:
	- sudo apt-get update -qq
	- sudo apt-get install -y libboost-python1.48-dev
install: pip install -r requirements.txt --use-mirrors
script:  python setup.py test
