language: python
python:
  - '3.7'
  - '3.6'
  - '3.5'
  - '3.4'
  - '3.3'
  - '3.2'
  - '2.7'
  - '2.6'
  - 'pypy2.7'
  - 'pypy3.5'
install:
  - pip install -r requirements.txt
before_script:
  - git submodule init
  - git submodule update
script:
  - python setup.py build_clib build_ext
  - pytest --benchmark-disable
  - python setup.py sdist bdist
deploy:
  - provider: pypi
    user: flier
    password:
      secure: MzQkLw7nm0B/4MOpaAQwzMLDPLEpTh3vfzqL4KVHV61sY8O1X7KTB2AdC7PvZcufviogBAMQF1lGjSuY/xGOBlkbrco0dqjPdBpaGq1w592gsA3D1y4tNJvFQrhkIKhxSjw7hM1PxThYtkDXlEfFprc5NopJ6oq0IZvEcgqgiz4=
    skip_cleanup: true
    on:
      tags: true
      repo: flier/pyfasthash
