sudo: false
language: python
python:
  - '3.7-dev'
  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'
  - 'pypy2'
  - 'pypy3'
install:
  - pip install -U setuptools pip
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest -v
