sudo: false
language: python
python:
  - '3.7-dev'
  - '3.6'
  - '3.5'
  - '3.4'
  - '3.3'
  - '3.2'
  - '2.7'
  - '2.6'
  - 'pypy2.7'
  - 'pypy3.5'
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest -v
